Rx is cool
windbreaker-io/rss-watcher pull request #6
Opened 2017-08-08 21:56 UTC by Epitrochoid

2017-08-09 00:25 UTC, mdaum requested changes
I would rename `test/unit/diff.js` to `rss-diff.js`, from what I have seen mostly in service-utils, windbreaker core, and npm watcher, the file structure of the test folder mirrors src

2017-08-09 00:42 UTC, ctdio approved these changes
Like @mdaum mentioned, change test file name to something like `rss-diff-test.js`. You should consider giving these PRs and branches more meaningful names other than "Rx is cool". Aside from the minor comment I made, things look good.

2017-08-09 00:42 UTC, charlieduong94 commented on test/unit/diff.js
> +
Some extra space here. `standard` wouldn't be too happy about this. btw you should totally add linting (in a separate PR).

2017-08-09 00:44 UTC, charlieduong94 commented
Regarding the better branch names, it would be good to associate your branches/commits with issue numbers from our trello board. Check out how we use https://www.npmjs.com/package/branch-name-commit-modifier to help with that in either core or the service utils repo.

2017-08-10 02:25 UTC, Druotic commented on test/unit/feed_diff.json
> +[
Consider moving these sample data files to a fixtures directory to avoid clutter as this repo grows in size.

2017-08-15 21:27 UTC, Epitrochoid commented on test/unit/diff.js
> +
Will make issue and do.

2017-08-15 21:29 UTC, Epitrochoid commented
Opening PR under better named branch.

2017-08-15 21:29 UTC, closed without merging